[package]
name = "compile-python"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
xrcf = { path = "../xrcf/" }
anyhow = "1.0.86"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
indoc = "2"
