pub mod block;
pub mod operation;
pub mod region;

pub use operation::Op;
pub use operation::Operation;

use anyhow::Result;

pub struct ModuleOp {
    operation: Operation,
}

impl Op for ModuleOp {
    fn from_operation(operation: Operation) -> Result<Self> {
        if operation.name() == "module" {
            Ok(Self { operation })
        } else {
            Err(anyhow::anyhow!("Expected module, got {}", operation.name()))
        }
    }
    fn name(&self) -> &'static str {
        "module"
    }
    // Note that if seeing things such as `getSymName`,
    // that these are generated by TableGen.
}